spring:
  cloud:
    gateway:
      routes:
        - id: comment-service
          uri: http://comment-service:8080
          predicates:
            - Path=/comment/**
  application:
    name: api-gateway
