spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: service-1
          uri: http://service1:8080
          predicates:
            - Path=/service1/**
        - id: service-2
          uri: http://service2:8080
          predicates:
            - Path=/service2/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
