spring:
  cloud:
    gateway:
      routes:
        - id: comment_service
          uri: http://localhost:8082
          predicates:
            - Path=/comment/**
  application:
    name: api-gateway
  web:
    cors:
      allowed-origins: "http://localhost:3000" # Explicitly allow your front-end origin
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
