server:
  port: 8080

spring:
  application:
    name: api-gateway

# Định nghĩa routing cho các service khác
spring:
  cloud:
    gateway:
      routes:
      - id: comment-service
        uri: http://comment-service:8082
        predicates:
        - Path=/comments/**
