spring:
  cloud:
    gateway:
      routes:
        - id: comment_service
          uri: http://comment-service:8082
          predicates:
            - Path=/comment/**
  application:
    name: api-gateway
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true