spring:
  cloud:
    gateway:
      routes:
        - id: comment_service
          # uri: http://localhost:8082
          uri: http://34.118.237.210:8082

          predicates:
            - Path=/comment/**
  application:
    name: api-gateway
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true