server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: comment-service
          uri: http://comment-service:8082
          predicates:
            - Path=/comment/**
  application:
    name: api-gateway
