spring:
  cloud:
    gateway:
      routes:
        - id: comment_service
          uri: http://34.118.236.190
          predicates:
            - Path=/comment/**
  application:
    name: api-gateway

