server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
      - id: comment-service
        uri: http://comment-service:8082
        predicates:
        - Path=/api/comment/**
      default-filters:
      - RewritePath=/api/(?<segment>.*), /${segment}
