server:
  port: 8080

spring:
  application:
    name: api-gateway

# API Gateway routes configuration
spring:
  cloud:
    gateway:
      routes:
        - id: comment-service
          uri: http://comment-service:8082
          predicates:
            - Path=/comment/**
