spring:
  cloud:
    gateway:
      routes:
        - id: comment-service
          uri: http://34.118.236.190
          # uri: http://localhost:8082

          predicates:
            - Path=/comment/**
  application:
    name: api-gateway

